# StudyProxy-Java 主配置文件

spring:
  config:
    import: optional:file:./config.yaml

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  messages:
    encoding: UTF-8

ocr:
  service:
    url: http://localhost:5000
